# Cloudflare Pages 配置文件
name = "llm-memory-calculator"

# 构建配置
[build]
command = "npm run build"
destination = "dist"

# 环境变量
[env.production]
NODE_ENV = "production"
VITE_APP_TITLE = "大模型内存估算器"
VITE_APP_VERSION = "1.0.0"

[env.preview]
NODE_ENV = "development"
VITE_APP_TITLE = "大模型内存估算器 (Preview)"
VITE_APP_VERSION = "1.0.0-preview"

# 重定向和路由规则（用于 SPA）
[[redirects]]
from = "/*"
to = "/index.html"
status = 200